import bcrypt from 'bcryptjs';

const COLLECTIONS = ['deposits','withdraws','trades','funds','chats','kycs'];
const rateMap = new Map();
function rateLimit(req, key, limit, windowMs){ const ip=req.headers.get('CF-Connecting-IP')||'unknown', k=key+':'+ip, n=Date.now(), old=rateMap.get(k); if(!old||n-old.start>windowMs){rateMap.set(k,{start:n,count:1});return true;} if(++old.count>limit)return false; return true; }
function secureResponse(resp){ const h=new Headers(resp.headers); h.set('X-Content-Type-Options','nosniff'); h.set('X-Frame-Options','DENY'); h.set('Referrer-Policy','strict-origin-when-cross-origin'); h.set('Permissions-Policy','camera=(), microphone=(), geolocation=()'); return new Response(resp.body,{status:resp.status,statusText:resp.statusText,headers:h}); }
const DEFAULT_SETTINGS = {
  siteName:'Binance Gold', site_name:'Binance Gold', welcomeText:'เริ่มปั่นพอร์ตกันเลย', welcome_text:'เริ่มปั่นพอร์ตกันเลย',
  aboutUs:'ยินดีต้อนรับสู่ Binance Gold', about_us:'ยินดีต้อนรับสู่ Binance Gold', withdrawFee:1, withdraw_fee:1, minWithdraw:10, min_withdraw:10,
  p2pAddress:'TLrt3947ScuuCguGRsKibuWvp9iZwmixXj', p2p_address:'TLrt3947ScuuCguGRsKibuWvp9iZwmixXj', p2pWithdrawFee:1, p2p_withdraw_fee:1,
  p2pMinWithdraw:10, p2p_min_withdraw:10, maintenance:false, autoTradeUserSettings:{},
  packages:'[{"percent":10,"amount":100},{"percent":30,"amount":1000},{"percent":40,"amount":2000},{"percent":60,"amount":4000},{"percent":70,"amount":6000},{"percent":80,"amount":10000}]',
  packages_json:'[{"percent":10,"amount":100},{"percent":30,"amount":1000},{"percent":40,"amount":2000},{"percent":60,"amount":4000},{"percent":70,"amount":6000},{"percent":80,"amount":10000}]',
  autoTradeEnabled:false,auto_trade_enabled:false,autoWinRate:50,auto_win_rate:50,autoTradeDelay:5,auto_trade_delay:5,autoTradeMode:'random',auto_trade_mode:'random'
};

const json = (data,status=200,headers={}) => new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'strict-origin-when-cross-origin',...headers}});
const now=()=>new Date().toISOString();
const parse=(s,f={})=>{try{return JSON.parse(s)}catch{return f}};
const strip=o=>{if(!o||typeof o!=='object')return o;const x={...o};delete x.password;delete x.password_hash;delete x.passwordHash;return x};
const id=(p)=>p+crypto.randomUUID().replaceAll('-','').slice(0,20);
async function sha256(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function cookie(name,value,maxAge=604800,secure=true){return `${name}=${value}; Path=/; HttpOnly;${secure?' Secure;':''} SameSite=Lax; Max-Age=${maxAge}`}
function cookieSecure(req){return new URL(req.url).protocol==='https:';}
function getCookies(req){return Object.fromEntries((req.headers.get('Cookie')||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1).trim())]}))}
function sessionCookieName(type){return type==='admin'?'bg_admin_sid':'bg_user_sid';}
function clearSessionCookies(req){
  const secure=cookieSecure(req);
  return [
    cookie(sessionCookieName('user'),' ',0,secure),
    cookie(sessionCookieName('admin'),' ',0,secure),
    cookie('bg_sid',' ',0,secure)
  ];
}
async function session(req,env,type){
  const c=getCookies(req);
  // New role-specific cookies allow a member and an Admin to stay signed in
  // simultaneously in the same browser. bg_sid is accepted only as a legacy
  // fallback for sessions created by older deployments.
  const token=c[sessionCookieName(type)] || c.bg_sid;
  if(!token)return null;
  const h=await sha256(token);
  const r=await env.DB.prepare('SELECT actor_type,actor_id,expires_at FROM sessions WHERE id_hash=?').bind(h).first();
  if(!r||r.actor_type!==type||new Date(r.expires_at)<=new Date())return null;
  return r;
}
async function requireSession(req,env,type){return await session(req,env,type)}
async function requireSuperAdmin(req,env){const s=await requireSession(req,env,'admin');if(!s)return null;const r=await env.DB.prepare('SELECT id,username,data FROM admins WHERE id=?').bind(s.actor_id).first();if(!r)return null;const d=parse(r.data,{});return d.role==='superadmin'?s:null}
function sameOrigin(req){const o=req.headers.get('Origin');return !o||o===new URL(req.url).origin}
async function body(req){const b=await req.json().catch(()=>({}));return b&&typeof b==='object'&&!Array.isArray(b)?b:{} }
function badKeys(o){if(!o||typeof o!=='object')return false;for(const k of Object.keys(o)){if(['__proto__','constructor','prototype'].includes(k)||badKeys(o[k]))return true}return false}
function userFromRow(r){if(!r)return null;const d=parse(r.data,{});return strip({...d,id:r.id,phone:r.phone,createdAt:d.createdAt||r.created_at})}
async function getUser(env,uid){return userFromRow(await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(uid).first())}
async function getRecord(env,col,rid){const r=await env.DB.prepare(`SELECT * FROM ${col} WHERE id=?`).bind(rid).first();return r?strip({...parse(r.data,{}),id:r.id,user_id:r.user_id,created_at:r.created_at,createdAt:parse(r.data,{}).createdAt||r.created_at}):null}
async function listRecords(env,col,uid,limit=500){let rs=uid?await env.DB.prepare(`SELECT * FROM ${col} WHERE user_id=? ORDER BY created_at DESC LIMIT ?`).bind(uid,limit).all():await env.DB.prepare(`SELECT * FROM ${col} ORDER BY created_at DESC LIMIT ?`).bind(limit).all();return rs.results.map(r=>strip({...parse(r.data,{}),id:r.id,user_id:r.user_id,created_at:r.created_at,createdAt:parse(r.data,{}).createdAt||r.created_at}))}
async function audit(env,actor,action,target,detail,ip){await env.DB.prepare('INSERT INTO audit_log(actor,action,target,detail,ip,created_at) VALUES(?,?,?,?,?,?)').bind(actor,action,target,JSON.stringify(detail||{}),ip||null,now()).run()}
async function notify(env,type,target,title,message){await env.DB.prepare('INSERT INTO notifications(id,type,target,title,message,created_at) VALUES(?,?,?,?,?,?)').bind(id('N'),type,target,title,message,now()).run()}
async function balance(env,uid,delta,type,ref,detail){const lid=id('L'),t=now(),dlt=Number(delta);if(!Number.isFinite(dlt))throw Error('invalid amount');const upd=env.DB.prepare("UPDATE users SET data=json_set(data,'$.balance',COALESCE(CAST(json_extract(data,'$.balance') AS REAL),0)+?) WHERE id=? AND COALESCE(CAST(json_extract(data,'$.balance') AS REAL),0)+? >= 0").bind(dlt,uid,dlt);const led=env.DB.prepare("INSERT INTO transaction_ledger(id,user_id,type,amount,balance_before,balance_after,reference_id,detail,created_at) SELECT ?,id,?,?,?,?,?,?,? FROM users WHERE id=? AND changes()>0").bind(lid,uid,type,dlt,0,0,ref||null,JSON.stringify(detail||{}),uid);const r=await env.DB.batch([upd,led]);if(!r[0].meta?.changes) {const exists=await env.DB.prepare('SELECT id FROM users WHERE id=?').bind(uid).first();if(!exists)throw Error('user not found');throw Error('insufficient balance');}const u=await getUser(env,uid);const after=Number(u.balance)||0;await env.DB.prepare('UPDATE transaction_ledger SET balance_after=?,balance_before=? WHERE id=?').bind(after,after-dlt,lid).run();return {user:u,ledgerId:lid}}
async function idem(req,env,op,fn){const k=req.headers.get('Idempotency-Key');if(k){const r=await env.DB.prepare('SELECT response FROM idempotency_keys WHERE key=?').bind(k).first();if(r)return parse(r.response,{})}const out=await fn();if(k)await env.DB.prepare('INSERT OR IGNORE INTO idempotency_keys(key,operation,response,created_at) VALUES(?,?,?,?)').bind(k,op,JSON.stringify(out),now()).run();return out}
async function ensureDefaults(env){const c=await env.DB.prepare('SELECT COUNT(*) n FROM settings').first();if(!c.n)await env.DB.batch(Object.entries(DEFAULT_SETTINGS).map(([k,v])=>env.DB.prepare('INSERT INTO settings(key,value) VALUES(?,?)').bind(k,JSON.stringify(v))));
  // One-time bootstrap/repair for the configured admin account. This fixes an
  // existing account with the wrong password without exposing plaintext credentials.
  const adminPassword = env.ADMIN_PASSWORD || env.ADMIN_SEED_PASSWORD;
  const adminUsername = String(env.ADMIN_USERNAME || '').trim();
  const boot = await env.DB.prepare("SELECT value FROM settings WHERE key='__admin_bootstrap_v2'").first();
  if(!boot && adminUsername && adminPassword){
    const a=await env.DB.prepare('SELECT * FROM admins WHERE username=?').bind(adminUsername).first();
    const h=await bcrypt.hash(String(adminPassword),10);
    if(!a){await env.DB.prepare('INSERT INTO admins(id,username,password_hash,data,created_at) VALUES(?,?,?,?,?)').bind(id('A'),adminUsername,h,JSON.stringify({name:'ผู้ดูแลระบบหลัก',role:'superadmin'}),now()).run();}
    else {await env.DB.prepare('UPDATE admins SET password_hash=?, data=? WHERE id=?').bind(h,JSON.stringify({...parse(a.data,{}),id:a.id,username:adminUsername,name:parse(a.data,{}).name||'ผู้ดูแลระบบหลัก',role:parse(a.data,{}).role||'superadmin'}),a.id).run();}
    await env.DB.prepare("INSERT OR REPLACE INTO settings(key,value) VALUES('__admin_bootstrap_v2',?)").bind(JSON.stringify({username:adminUsername,at:now()})).run();
  }
}
async function login(env,type,identifier,password){
  let r=type==='user'
    ? await env.DB.prepare('SELECT * FROM users WHERE phone=?').bind(identifier).first()
    : await env.DB.prepare('SELECT * FROM admins WHERE username=?').bind(identifier).first();

  let valid = !!(r && r.password_hash && await bcrypt.compare(String(password), r.password_hash));

  // Repair/create the configured bootstrap Admin only when the submitted
  // credentials exactly match the server-side secret. This also repairs an
  // Admin whose password was changed previously, without storing plaintext.
  if(type==='admin' && !valid){
    const configuredUsername=String(env.ADMIN_USERNAME||'').trim();
    const configuredPassword=env.ADMIN_PASSWORD||env.ADMIN_SEED_PASSWORD||'';
    if(configuredUsername && configuredPassword && String(identifier).trim()===configuredUsername && String(password)===String(configuredPassword)){
      const existing=await env.DB.prepare('SELECT * FROM admins WHERE username=?').bind(configuredUsername).first();
      const h=await bcrypt.hash(String(configuredPassword),10);
      if(existing){
        const d=parse(existing.data,{});
        await env.DB.prepare('UPDATE admins SET password_hash=?, data=? WHERE id=?').bind(h,JSON.stringify({...d,id:existing.id,username:configuredUsername,name:d.name||'ผู้ดูแลระบบหลัก',role:d.role||'superadmin'}),existing.id).run();
      }else{
        const aid=id('A');
        await env.DB.prepare('INSERT INTO admins(id,username,password_hash,data,created_at) VALUES(?,?,?,?,?)').bind(aid,configuredUsername,h,JSON.stringify({id:aid,username:configuredUsername,name:'ผู้ดูแลระบบหลัก',role:'superadmin'}),now()).run();
      }
      r=await env.DB.prepare('SELECT * FROM admins WHERE username=?').bind(configuredUsername).first();
      valid=!!(r && r.password_hash && await bcrypt.compare(String(password),r.password_hash));
    }
  }

  if(!valid)return null;
  const raw=crypto.randomUUID()+crypto.randomUUID(),h=await sha256(raw),sid=r.id;
  await env.DB.prepare('INSERT INTO sessions(id_hash,actor_type,actor_id,expires_at,created_at) VALUES(?,?,?,?,?)').bind(h,type,sid,new Date(Date.now()+7*86400000).toISOString(),now()).run();
  return {token:raw,user:type==='user'?userFromRow(r):strip({...parse(r.data,{}),id:r.id,username:r.username})};
}

export default {async fetch(req,env){
  await ensureDefaults(env);
  const u=new URL(req.url); const path=u.pathname;
  if(path.startsWith('/api/')){
    const isAuth=/^\/api\/(auth|admin\/login)/.test(path);
    if(!rateLimit(req,isAuth?'auth':'api',isAuth?20:300,15*60*1000)) return json({ok:false,error:'too many requests, please try again later'},429,{'Retry-After':'900'});
    if(!sameOrigin(req)&&req.method!=='GET')return json({ok:false,error:'origin rejected'},403);
    try{return await api(req,env,u);}catch(e){console.error(e);return json({ok:false,error:e.message||'internal error'},500)}
  }
  if(path==='/'||path==='/index.html'||path==='/admin'||path==='/admin.html'){const target=(path==='/admin'||path==='/admin.html')?'/admin.html':'/index.html';const r=new Request(new URL(target,u),req);const resp=await env.ASSETS.fetch(r);const html=await resp.text();const out=html.includes('/api-db.js')?html:(html.includes('</body>')?html.replace('</body>','<script src="/api-db.js"></script></body>'):html+'<script src="/api-db.js"></script>');return new Response(out,{status:resp.status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-cache'}})}
  return env.ASSETS.fetch(req);
}}

async function api(req,env,u){const p=u.pathname.replace(/^\/api\/?/,'').split('/').filter(Boolean);const method=req.method;
  if(p[0]==='health')return json({ok:true,environment:env.APP_ENV||'production'});
  if(p[0]==='auth'&&p[1]==='register'&&method==='POST'){const b=await body(req);if(badKeys(b)||!b.name||!b.phone||!b.password||String(b.password).length<4)return json({ok:false,error:'validation failed'},400);const phone=String(b.phone).trim();const ex=await env.DB.prepare('SELECT id FROM users WHERE phone=?').bind(phone).first();if(ex)return json({ok:false,error:'phone already registered'},409);const h=await bcrypt.hash(String(b.password),10),uid=phone,t=now(),data={id:uid,name:String(b.name).trim(),phone,balance:0,vip:1,kycStatus:'none',avatar:null,createdAt:t};await env.DB.prepare('INSERT INTO users(id,phone,password_hash,data,created_at) VALUES(?,?,?,?,?)').bind(uid,phone,h,JSON.stringify(data),t).run();const l=await login(env,'user',phone,String(b.password));await notify(env,'register',uid,'สมาชิกใหม่',`${data.name} สมัครสมาชิก`);return json({ok:true,user:data},201,{'set-cookie':cookie(sessionCookieName('user'),l.token,604800,cookieSecure(req))})}
  if(p[0]==='auth'&&p[1]==='login'&&method==='POST'){const b=await body(req);const l=await login(env,'user',String(b.phone||'').trim(),String(b.password||''));if(!l)return json({ok:false,error:'invalid credentials'},401);return json({ok:true,user:l.user},200,{'set-cookie':cookie(sessionCookieName('user'),l.token,604800,cookieSecure(req))})}
  if(p[0]==='auth'&&p[1]==='me'&&method==='GET'){const s=await requireSession(req,env,'user');if(!s)return json({ok:false,error:'unauthorized'},401);const user=await getUser(env,s.actor_id);return user?json({ok:true,user}):json({ok:false,error:'unauthorized'},401)}
  if(p[0]==='auth'&&p[1]==='logout'&&method==='POST'){const c=getCookies(req);for(const name of [sessionCookieName('user'),'bg_sid']){if(c[name])await env.DB.prepare('DELETE FROM sessions WHERE id_hash=?').bind(await sha256(c[name])).run();}return new Response(JSON.stringify({ok:true}),{status:200,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','set-cookie':clearSessionCookies(req)}})}
  if(p[0]==='admin'&&p[1]==='login'&&method==='POST'){const b=await body(req);const l=await login(env,'admin',String(b.username||'').trim(),String(b.password||''));if(!l)return json({ok:false,error:'invalid credentials'},401);await audit(env,'admin:'+l.user.id,'admin_login',l.user.username,{},req.headers.get('CF-Connecting-IP'));return json({ok:true,admin:l.user},200,{'set-cookie':cookie(sessionCookieName('admin'),l.token,604800,cookieSecure(req))})}
  if(p[0]==='admin'&&p[1]==='me'&&method==='GET'){const s=await requireSession(req,env,'admin');if(!s)return json({ok:false,error:'unauthorized'},401);const r=await env.DB.prepare('SELECT * FROM admins WHERE id=?').bind(s.actor_id).first();return r?json({ok:true,admin:strip({...parse(r.data,{}),id:r.id,username:r.username})}):json({ok:false,error:'unauthorized'},401)}
  if(p[0]==='admin'&&p[1]==='logout'&&method==='POST'){const c=getCookies(req);for(const name of [sessionCookieName('admin'),'bg_sid']){if(c[name])await env.DB.prepare('DELETE FROM sessions WHERE id_hash=?').bind(await sha256(c[name])).run();}return new Response(JSON.stringify({ok:true}),{status:200,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','set-cookie':clearSessionCookies(req)}})}
  if(p[0]==='settings'&&method==='GET'){const rs=await env.DB.prepare('SELECT key,value FROM settings').all();const o={};for(const r of rs.results){if(String(r.key).startsWith('__'))continue;o[r.key]=parse(r.value,r.value);}return json(o)}
  const user=await requireSession(req,env,'user'), admin=await requireSession(req,env,'admin');
  if(p[0]==='settings'&&method==='PUT'){if(!await requireSuperAdmin(req,env))return json({ok:false,error:'superadmin required'},403);const b=await body(req);await env.DB.batch(Object.entries(b).map(([k,v])=>env.DB.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(k,JSON.stringify(v))));await audit(env,'admin:'+admin.actor_id,'update_settings','settings',{keys:Object.keys(b)},req.headers.get('CF-Connecting-IP'));const rs2=await env.DB.prepare('SELECT key,value FROM settings').all();const o2={};for(const r of rs2.results)o2[r.key]=parse(r.value,r.value);return json(o2)}
  if(p[0]==='users'&&method==='GET'){const q=String(u.searchParams.get('q')||'');if(admin){const lim=Math.min(Number(u.searchParams.get('limit')||500),5000);let rs=q?await env.DB.prepare("SELECT * FROM users WHERE phone LIKE ? OR id LIKE ? OR json_extract(data,'$.name') LIKE ? ORDER BY created_at DESC LIMIT ?").bind('%'+q+'%','%'+q+'%','%'+q+'%',lim).all():await env.DB.prepare('SELECT * FROM users ORDER BY created_at DESC LIMIT ?').bind(lim).all();return json(rs.results.map(userFromRow))}if(user&&!q){const me=await getUser(env,user.actor_id);return me?json([me]):json([])}return json({ok:false,error:'forbidden'},403)}
  if(p[0]==='users'&&p.length===2&&method==='GET'){if(!admin&&(!user||user.actor_id!==p[1]))return json({ok:false,error:'forbidden'},403);const x=await getUser(env,p[1]);return x?json(x):json({ok:false,error:'not found'},404)}
  if(p[0]==='users'&&p.length===2&&method==='PUT'){if(!admin&&(!user||user.actor_id!==p[1]))return json({ok:false,error:'forbidden'},403);const b=await body(req);if(Object.hasOwn(b,'balance')&&!admin)return json({ok:false,error:'balance transaction required'},403);if(!admin){const allow=['name','avatar','password','kycStatus'];const bad=Object.keys(b).filter(k=>!allow.includes(k));if(bad.length)return json({ok:false,error:'field not allowed',fields:bad},403);if(Object.hasOwn(b,'kycStatus')&&b.kycStatus!=='pending')return json({ok:false,error:'field not allowed',fields:['kycStatus']},403);}const r=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(p[1]).first();if(!r)return json({ok:false,error:'not found'},404);const d=parse(r.data,{});let delta=null;if(Object.hasOwn(b,'balance')){delta=Number(b.balance)-(Number(d.balance)||0);delete b.balance}const nd={...d,...strip(b)};const stm=[env.DB.prepare('UPDATE users SET phone=?,data=? WHERE id=?').bind(nd.phone||r.phone,JSON.stringify(nd),p[1])];if(delta){}await env.DB.batch(stm);let out=await getUser(env,p[1]);if(delta)out=(await balance(env,p[1],delta,'admin_adjustment',null,{actor:admin.actor_id})).user;return json(out)}
  if(p[0]==='transactions'&&method==='GET'){if(!user&&!admin)return json({ok:false,error:'unauthorized'},401);const uid=admin?(u.searchParams.get('user_id')||null):user.actor_id;if(!uid)return json([]);return json((await env.DB.prepare('SELECT * FROM transaction_ledger WHERE user_id=? ORDER BY created_at DESC LIMIT 500').bind(uid).all()).results)}
  if(p[0]==='notifications'&&method==='GET'){if(!admin)return json({ok:false,error:'forbidden'},403);return json((await env.DB.prepare('SELECT * FROM notifications ORDER BY created_at DESC LIMIT 200').all()).results)}
  if(p[0]==='wallet'&&p[1]==='withdraw'&&method==='POST'){if(!user)return json({ok:false,error:'unauthorized'},401);const b=await body(req),amount=Number(b.amount),fee=Number(b.fee||1);if(!Number.isFinite(amount)||amount<=0)return json({ok:false,error:'invalid amount'},400);const rec={...b,amount,status:'pending',reservedAmount:amount+fee,user_id:user.actor_id,userId:user.actor_id,createdAt:b.createdAt||now(),created_at:b.created_at||now()};const out=await idem(req,env,'wallet_withdraw',async()=>{const rid=String(rec.id||id('W'));delete rec.fee;await env.DB.prepare('INSERT INTO withdraws(id,user_id,data,created_at) VALUES(?,?,?,?)').bind(rid,user.actor_id,JSON.stringify({...rec,id:rid}),rec.created_at).run();const bal=await balance(env,user.actor_id,-amount-fee,'withdraw_reserve',rid,{amount,fee});await notify(env,'withdraw',user.actor_id,'รายการถอนเงินใหม่',`ถอน ${amount} USDT`);return {ok:true,withdraw:{...rec,id:rid},user:bal.user}});return json(out,201)}
  if(p[0]==='wallet'&&p[1]==='trade'&&method==='POST'){if(!user)return json({ok:false,error:'unauthorized'},401);const b=await body(req),amount=Number(b.amount);if(!Number.isFinite(amount)||amount<=0)return json({ok:false,error:'invalid amount'},400);const out=await idem(req,env,'wallet_trade',async()=>{const rid=String(b.id||id('T')),t={...b,id:rid,user_id:user.actor_id,userId:user.actor_id,status:b.status||'pending',createdAt:b.createdAt||now(),created_at:b.created_at||now()};const all=await env.DB.prepare('SELECT value FROM settings WHERE key=?').bind('autoTradeUserSettings').first();const ats=parse(all?.value,{}),us=ats[user.actor_id];if(us?.result){t.result=us.result==='random'?(Math.random()*100<(Number(us.winRate)||50)?'win':'lose'):us.result;t.resultSetAt=now()}await env.DB.prepare('INSERT INTO trades(id,user_id,data,created_at) VALUES(?,?,?,?)').bind(rid,user.actor_id,JSON.stringify(t),t.created_at).run();const bal=await balance(env,user.actor_id,-amount,'trade_open',rid,{symbol:t.symbol,type:t.type});await notify(env,'trade',user.actor_id,'รายการซื้อขายใหม่',`${t.symbol||''} ${amount} USDT`);return {ok:true,trade:t,user:bal.user}});return json(out,201)}
  if(p[0]==='wallet'&&p[1]==='trades'&&p[3]==='settle'&&method==='POST'){if(!user)return json({ok:false,error:'unauthorized'},401);const t=await getRecord(env,'trades',p[2]);if(!t)return json({ok:false,error:'not found'},404);if(t.user_id!==user.actor_id)return json({ok:false,error:'forbidden'},403);if(t.status==='closed')return json({ok:true,trade:t,user:await getUser(env,user.actor_id)});if(!t.endTime||new Date(t.endTime)>new Date())return json({ok:false,error:'trade not due'},409);const result=t.result==='win'?'win':'lose',amount=Number(t.amount)||0,pct=Number(t.percent||(t.package&&t.package.percent)||0),profit=result==='win'?amount*pct/100:-amount;await env.DB.prepare('UPDATE trades SET data=? WHERE id=?').bind(JSON.stringify({...t,status:'closed',profit,closed_at:now()}),t.id).run();const u=result==='win'?(await balance(env,user.actor_id,amount+profit,'trade_settlement',t.id,{result})).user:await getUser(env,user.actor_id);return json({ok:true,trade:{...t,status:'closed',profit},user:u})}
  if(p[0]==='wallet'&&p[1]==='funds'&&p[3]==='settle'&&method==='POST'){if(!user)return json({ok:false,error:'unauthorized'},401);const f=await getRecord(env,'funds',p[2]);if(!f)return json({ok:false,error:'not found'},404);if(f.user_id!==user.actor_id)return json({ok:false,error:'forbidden'},403);if(f.status==='completed')return json({ok:true,fund:f,user:await getUser(env,user.actor_id)});if(!f.result||!f.endTime||new Date(f.endTime)>new Date())return json({ok:false,error:'fund not due'},409);const amount=Number(f.amount)||0,profit=amount*(Number(f.percent)||0)/100,x={...f,status:'completed',profit:f.result==='win'?profit:-amount,settledAt:now()};await env.DB.prepare('UPDATE funds SET data=? WHERE id=?').bind(JSON.stringify(x),f.id).run();const usr=f.result==='win'?(await balance(env,f.user_id,amount+profit,'fund_settlement',f.id,{result:f.result})).user:await getUser(env,f.user_id);return json({ok:true,fund:x,user:usr})}
  if(p[0]==='wallet'&&p[1]==='fund'&&method==='POST'){if(!user)return json({ok:false,error:'unauthorized'},401);const b=await body(req),amount=Number(b.amount);if(!Number.isFinite(amount)||amount<=0)return json({ok:false,error:'invalid amount'},400);const out=await idem(req,env,'wallet_fund',async()=>{const rid=String(b.id||id('F')),t={...b,id:rid,user_id:user.actor_id,userId:user.actor_id,status:'active',createdAt:b.createdAt||now(),created_at:b.created_at||now()};await env.DB.prepare('INSERT INTO funds(id,user_id,data,created_at) VALUES(?,?,?,?)').bind(rid,user.actor_id,JSON.stringify(t),t.created_at).run();const bal=await balance(env,user.actor_id,-amount,'fund_open',rid,{days:t.days,percent:t.percent});return {ok:true,fund:t,user:bal.user}});return json(out,201)}
  if(p[0]==='admin'&&p[1]==='deposits'&&p[3]==='approve'&&method==='POST'){if(!admin)return json({ok:false,error:'forbidden'},403);const d=await getRecord(env,'deposits',p[2]);if(!d)return json({ok:false,error:'not found'},404);if(d.status==='approved')return json({ok:true,deposit:d,user:await getUser(env,d.user_id)});if(d.status!=='pending')return json({ok:false,error:'already processed'},409);await env.DB.prepare('UPDATE deposits SET data=? WHERE id=?').bind(JSON.stringify({...d,status:'approved',approvedAt:now()}),d.id).run();const bal=await balance(env,d.user_id,Number(d.amount)||0,'deposit',d.id,{type:d.type||'deposit'});await audit(env,'admin:'+admin.actor_id,'approve_deposit',d.id,{},req.headers.get('CF-Connecting-IP'));return json({ok:true,deposit:{...d,status:'approved'},user:bal.user})}
  if(p[0]==='admin'&&p[1]==='deposits'&&p[3]==='reject'&&method==='POST'){if(!admin)return json({ok:false,error:'forbidden'},403);const d=await getRecord(env,'deposits',p[2]);if(!d)return json({ok:false,error:'not found'},404);if(d.status!=='pending')return json({ok:true,deposit:d});const x={...d,status:'rejected',rejectedAt:now()};await env.DB.prepare('UPDATE deposits SET data=? WHERE id=?').bind(JSON.stringify(x),d.id).run();await audit(env,'admin:'+admin.actor_id,'reject_deposit',d.id,{},req.headers.get('CF-Connecting-IP'));return json({ok:true,deposit:x})}
  if(p[0]==='admin'&&p[1]==='withdraws'&&p[3]==='approve'&&method==='POST'){if(!admin)return json({ok:false,error:'forbidden'},403);const w=await getRecord(env,'withdraws',p[2]);if(!w)return json({ok:false,error:'not found'},404);if(w.status!=='pending')return json({ok:true,withdraw:w});const x={...w,status:'approved',approvedAt:now()};await env.DB.prepare('UPDATE withdraws SET data=? WHERE id=?').bind(JSON.stringify(x),w.id).run();await audit(env,'admin:'+admin.actor_id,'approve_withdraw',w.id,{},req.headers.get('CF-Connecting-IP'));return json({ok:true,withdraw:x})}
  if(p[0]==='admin'&&p[1]==='withdraws'&&p[3]==='reject'&&method==='POST'){if(!admin)return json({ok:false,error:'forbidden'},403);const w=await getRecord(env,'withdraws',p[2]);if(!w)return json({ok:false,error:'not found'},404);if(w.status==='approved')return json({ok:false,error:'cannot reject approved'},409);if(w.status==='rejected')return json({ok:true,withdraw:w});const x={...w,status:'rejected',rejectedAt:now()};await env.DB.prepare('UPDATE withdraws SET data=? WHERE id=?').bind(JSON.stringify(x),w.id).run();const bal=await balance(env,w.user_id,Number(w.reservedAmount||(Number(w.amount)||0)+1),'withdraw_refund',w.id,{});await audit(env,'admin:'+admin.actor_id,'reject_withdraw',w.id,{},req.headers.get('CF-Connecting-IP'));return json({ok:true,withdraw:x,user:bal.user})}
  if(p[0]==='admin'&&p[1]==='trades'&&p[3]==='settle'&&method==='POST'){if(!admin)return json({ok:false,error:'forbidden'},403);const t=await getRecord(env,'trades',p[2]);if(!t)return json({ok:false,error:'not found'},404);if(t.status==='closed')return json({ok:true,trade:t});const b=await body(req),result=b.result==='win'?'win':'lose',amount=Number(t.amount)||0,profit=result==='win'?amount*(Number(t.percent||(t.package&&t.package.percent)||0))/100:-amount;const x={...t,status:'closed',profit,closed_at:now()};await env.DB.prepare('UPDATE trades SET data=? WHERE id=?').bind(JSON.stringify(x),t.id).run();const usr=result==='win'?(await balance(env,t.user_id,amount+profit,'trade_settlement',t.id,{result})).user:await getUser(env,t.user_id);await audit(env,'admin:'+admin.actor_id,'settle_trade',t.id,{result},req.headers.get('CF-Connecting-IP'));return json({ok:true,trade:x,user:usr})}
  if(p[0]==='admin'&&p[1]==='funds'&&p[3]==='set-result'&&method==='POST'){if(!admin)return json({ok:false,error:'forbidden'},403);const f=await getRecord(env,'funds',p[2]);if(!f)return json({ok:false,error:'not found'},404);const b=await body(req),x={...f,result:b.result==='win'?'win':'lose',resultSetAt:now()};await env.DB.prepare('UPDATE funds SET data=? WHERE id=?').bind(JSON.stringify(x),f.id).run();await audit(env,'admin:'+admin.actor_id,'set_fund_result',f.id,{result:x.result},req.headers.get('CF-Connecting-IP'));return json({ok:true,fund:x})}
  if(p[0]==='admin'&&p[1]==='funds'&&p[3]==='settle'&&method==='POST'){if(!admin)return json({ok:false,error:'forbidden'},403);const f=await getRecord(env,'funds',p[2]);if(!f)return json({ok:false,error:'not found'},404);if(f.status==='completed')return json({ok:true,fund:f});if(!f.result||!f.endTime||new Date(f.endTime)>new Date())return json({ok:false,error:'fund not due'},409);const amount=Number(f.amount)||0,profit=amount*(Number(f.percent)||0)/100,x={...f,status:'completed',profit:f.result==='win'?profit:-amount,settledAt:now()};await env.DB.prepare('UPDATE funds SET data=? WHERE id=?').bind(JSON.stringify(x),f.id).run();const usr=f.result==='win'?(await balance(env,f.user_id,amount+profit,'fund_settlement',f.id,{result:f.result})).user:await getUser(env,f.user_id);return json({ok:true,fund:x,user:usr})}
  if(COLLECTIONS.includes(p[0])){if(!user&&!admin)return json({ok:false,error:'unauthorized'},401);const col=p[0];if(method==='GET'){const uid=admin?(u.searchParams.get('user_id')||null):user.actor_id;return json(await listRecords(env,col,uid,5000))}if(method==='POST'){const b=await body(req);if(badKeys(b))return json({ok:false,error:'invalid field name'},400);const uid=admin?(b.user_id||b.userId):user.actor_id;if(!uid)return json({ok:false,error:'user required'},400);const rid=String(b.id||id(col.slice(0,1).toUpperCase())),t=b.created_at||b.createdAt||now(),data=strip({...b,id:rid,user_id:uid,userId:uid,createdAt:t,created_at:t});await env.DB.prepare(`INSERT INTO ${col}(id,user_id,data,created_at) VALUES(?,?,?,?)`).bind(rid,uid,JSON.stringify(data),t).run();if(['deposits','withdraws','kycs'].includes(col))await notify(env,col,uid,'รายการใหม่',`${col}: ${rid}`);return json(data,201)}if(p.length===2&&method==='GET'){const r=await getRecord(env,col,p[1]);if(!r)return json({ok:false,error:'not found'},404);if(!admin&&r.user_id!==user.actor_id)return json({ok:false,error:'forbidden'},403);return json(r)}if(p.length===2&&method==='PUT'){const r=await getRecord(env,col,p[1]);if(!r)return json({ok:false,error:'not found'},404);if(!admin&&r.user_id!==user.actor_id)return json({ok:false,error:'forbidden'},403);const b=await body(req);if(badKeys(b))return json({ok:false,error:'invalid field name'},400);if(!admin){const ALLOWED={deposits:['slip_url','slipUrl','note'],withdraws:['bank_info','bankInfo','address','note'],trades:[],funds:[],chats:['message','type'],kycs:['fullName','idNumber','dob','front_image_url','frontImageUrl','back_image_url','backImageUrl','selfie_image_url','selfieImageUrl']};const allow=ALLOWED[col]||[];const bad=Object.keys(b).filter(k=>!allow.includes(k));if(bad.length)return json({ok:false,error:'field not allowed',fields:bad},403);}const x=strip({...r,...b,id:r.id,user_id:r.user_id,userId:r.user_id});await env.DB.prepare(`UPDATE ${col} SET data=? WHERE id=?`).bind(JSON.stringify(x),r.id).run();if(admin)await audit(env,'admin:'+admin.actor_id,'edit_'+col,r.id,{fields:Object.keys(b)},req.headers.get('CF-Connecting-IP'));return json(x)}}
  if(p[0]==='admin'&&p[1]==='chats'&&method==='DELETE'){if(!admin)return json({ok:false,error:'forbidden'},403);const uid=String(u.searchParams.get('user_id')||'');if(!uid)return json({ok:false,error:'user_id required'},400);const r=await env.DB.prepare('DELETE FROM chats WHERE user_id=?').bind(uid).run();await audit(env,'admin:'+admin.actor_id,'delete_chats',uid,{},req.headers.get('CF-Connecting-IP'));return json({ok:true,deleted:r.meta?.changes||0})}
  if(p[0]==='admins'&&method==='GET'){if(!admin)return json({ok:false,error:'forbidden'},403);const rs=await env.DB.prepare('SELECT * FROM admins ORDER BY created_at ASC').all();return json(rs.results.map(r=>strip({...parse(r.data,{}),id:r.id,username:r.username})))}
  if(p[0]==='admins'&&method==='POST'){if(!await requireSuperAdmin(req,env))return json({ok:false,error:'superadmin required'},403);const b=await body(req);if(!b.username||!b.password||String(b.password).length<4)return json({ok:false,error:'validation failed'},400);const h=await bcrypt.hash(String(b.password),10),rid=id('A'),t=now(),data={id:rid,username:String(b.username).trim(),name:b.name||'',role:b.role||'admin',createdAt:t};try{await env.DB.prepare('INSERT INTO admins(id,username,password_hash,data,created_at) VALUES(?,?,?,?,?)').bind(rid,data.username,h,JSON.stringify(data),t).run();await audit(env,'admin:'+admin.actor_id,'create_admin',rid,{username:data.username},req.headers.get('CF-Connecting-IP'));return json(strip(data),201)}catch(e){return json({ok:false,error:'username already exists'},409)}}
  if(p[0]==='admins'&&p.length===2&&method==='DELETE'){if(!await requireSuperAdmin(req,env))return json({ok:false,error:'superadmin required'},403);if(p[1]===admin.actor_id)return json({ok:false,error:'cannot delete yourself'},400);await env.DB.prepare('DELETE FROM admins WHERE id=?').bind(p[1]).run();await audit(env,'admin:'+admin.actor_id,'delete_admin',p[1],{},req.headers.get('CF-Connecting-IP'));return json({ok:true})}
  if(p[0]==='audit-log'&&method==='GET'){if(!admin)return json({ok:false,error:'forbidden'},403);return json((await env.DB.prepare('SELECT * FROM audit_log ORDER BY id DESC LIMIT 200').all()).results)}
  return json({ok:false,error:'not found'},404);
}
